# Generated by Django 2.0.7 on 2018-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.BigIntegerField(),
        ),
    ]
